### ISSUE TITLE
CTD When Fence is used as disguise block 

### ISSUE THREAD

**Issue by RazE-Velox** [MC-U-Team/Draw-Bridge#18]
If a fence is used as the disguise block game CTDs and that state is saved until mod is removed

**Comment by HyCraftHD** [comment]
Can you specify that? And please fill in a issue report with alle the mod information.

**Comment by Vanblam** [comment]
What he means is if you use a wall or a fence as a disguise the game crashes. Then you can't load back into your game or it will crash over and over until you remove the mod. That just happened to me. I can paste the crash report.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93)
	at net.minecraft.client.renderer.model.multipart.PropertyValueCondition.func_212483_a(SourceFile:61)
	at net.minecraft.client.renderer.model.multipart.PropertyValueCondition$$Lambda$5760/1591095266.test(Unknown Source)
	at net.minecraft.client.renderer.model.MultipartBakedModel.func_200117_a(SourceFile:56)
	at net.minecraftforge.client.extensions.IForgeBakedModel.getQuads(IForgeBakedModel.java:50)
	at info.u_team.draw_bridge.model.DrawBridgeModel.getQuads(DrawBridgeModel.java:26)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:73)

-- Block model being tesselated --
Details:
	Block: Block{drawbridge:draw_bridge}[facing=north]
	Block location: World: (-665,68,204), Chunk: (at 7,4,12 in -42,12; contains blocks -672,0,192 to -657,255,207), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51)

-- Block being tesselated --
Details:
	Block: Block{drawbridge:draw_bridge}[facing=north]
	Block location: World: (-665,68,204), Chunk: (at 7,4,12 in -42,12; contains blocks -672,0,192 to -657,255,207), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:62)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164)
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:784)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:887)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Xerraldis'/118, l='MpServer', x=-665.99, y=68.00, z=207.04]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 3621640091195562791
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,70,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 522398 game time, 6648 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1397338694.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
